// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package ru.hse.servers.protocol.message;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.hse.servers.protocol.message.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 len = 1;</code>
   * @return Whether the len field is set.
   */
  boolean hasLen();
  /**
   * <code>required int32 len = 1;</code>
   * @return The len.
   */
  int getLen();

  /**
   * <code>repeated int32 array = 2;</code>
   * @return A list containing the array.
   */
  java.util.List<java.lang.Integer> getArrayList();
  /**
   * <code>repeated int32 array = 2;</code>
   * @return The count of array.
   */
  int getArrayCount();
  /**
   * <code>repeated int32 array = 2;</code>
   * @param index The index of the element to return.
   * @return The array at the given index.
   */
  int getArray(int index);
}
