// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package ru.hse.servers.protocol.message;

public final class MessageProtocol {
  private MessageProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_hse_servers_protocol_message_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_hse_servers_protocol_message_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\037ru.hse.servers.protocol" +
      ".message\":\n\007Message\022\020\n\010clientId\030\001 \002(\005\022\016\n" +
      "\006taskId\030\002 \002(\005\022\r\n\005array\030\003 \003(\005B\023B\017MessageP" +
      "rotocolP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ru_hse_servers_protocol_message_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ru_hse_servers_protocol_message_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_hse_servers_protocol_message_Message_descriptor,
        new java.lang.String[] { "ClientId", "TaskId", "Array", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
